ALTER TABLE products ADD COLUMN IF NOT EXISTS views INTEGER DEFAULT 0;
ALTER TABLE products ADD COLUMN IF NOT EXISTS clicks INTEGER DEFAULT 0;
CREATE INDEX IF NOT EXISTS idx_products_views ON products(views);
